<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>whatsapp-parser</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <groupId>org.apache.maven.plugins</groupId>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <groupId>org.apache.maven.plugins</groupId>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>io.github.vitalijr2.textforge</groupId>
      <artifactId>chat-parser-api</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <artifactId>annotations</artifactId>
      <groupId>org.jetbrains</groupId>
    </dependency>
  </dependencies>
  <name>WhatsApp Parser</name>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>chat-parser</artifactId>
    <groupId>io.github.vitalijr2.textforge</groupId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
</project>